---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs


inputs:
- name: upgrade-tile
- name: pivnet-product

params:
  ENABLE_ERRANDS:
  OPSMAN_CLIENT_ID:
  OPSMAN_CLIENT_SECRET:
  OPSMAN_PASSWORD:
  OPSMAN_USERNAME:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:

run:
  path: upgrade-tile/tasks/toggle-errands/task.sh
